spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AE-CourseModel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none